version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env  
    environment:
      - DATABASE_URL=postgresql+asyncpg://app_user:saad123@db:5432/stock_db 
  
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: stock_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: saad123
    ports:
      - "5432:5432"
