
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env  
    environment:
      - POSTGRES_HOST=service_name_of_db
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=saad123
      - POSTGRES_DB=stock_db
    networks:
      - practice
  
  db:
    image: postgres:13
    environment:
      - POSTGRES_HOST=service_name_of_db
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=saad123
      - POSTGRES_DB=stock_db
    env_file:
      - ./.env
    networks:
      - practice
networks:
  practice:
